In [2]:
import numpy as np

In [4]:
np.empty((2,3,2))

array([[[6.23042070e-307, 3.56043053e-307],
        [1.60219306e-306, 7.56571288e-307],
        [1.89146896e-307, 1.37961302e-306]],

       [[1.05699242e-307, 8.01097889e-307],
        [1.60219035e-306, 1.33511969e-306],
        [1.78022206e-306, 1.60219035e-306]]])

In [5]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [7]:
a = np.random.randn(2,2)
print(a)
np.ones_like(a)

[[-2.40048019 -0.98880475]
 [-0.81937624  0.30386596]]


array([[1., 1.],
       [1., 1.]])

In [8]:
b = np.random.randn(2,2)
print(b)
np.zeros_like(b)

[[-0.7876373   0.05237788]
 [-1.08981825  0.21615885]]


array([[0., 0.],
       [0., 0.]])

In [9]:
np.full((3,4),12)

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [10]:
np.eye(16)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [12]:
np.linalg.inv(np.eye(4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
n = np.array(['1.23','-1.2'], dtype=np.string_)
n.astype(float)

array([ 1.23, -1.2 ])

In [14]:
n

array([b'1.23', b'-1.2'], dtype='|S4')

In [15]:
e = np.random.randn(2,3)
print(e)
f = 1 /e
print(f)

[[-0.41975808  0.86857594  0.17722016]
 [ 0.5206835   1.14888052  0.13683863]]
[[-2.38232457  1.15130981  5.64269889]
 [ 1.92055251  0.87041253  7.30787777]]


In [16]:
e - np.random.randn(2,3)

array([[-0.00502928,  2.05879277,  0.68432055],
       [ 1.66040347,  2.81563703, -1.41470154]])

In [18]:
x = np.array([2,3,4,5,6,7,8,9,0])
print(x)
x[3:5] = 12
y = x[3:5]
print(y)
y[1] = 66
print(x)

[2 3 4 5 6 7 8 9 0]
[12 12]
[ 2  3  4 12 66  7  8  9  0]


In [20]:
k = x[2:5].copy()
print(k,x)
k[1] = 25
print(k,x)

[ 4 12 66] [ 2  3  4 12 66  7  8  9  0]
[ 4 25 66] [ 2  3  4 12 66  7  8  9  0]


In [30]:
n = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('3 dimension',n)
print('Get first depth',n[0])
print('show first depth, second row, third element',n[0,1,2])

3 dimension [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Get first depth [[1 2 3]
 [4 5 6]]
show first depth, second row, third element 6


In [27]:
m = np.random.randn(3,2)
print('2d array',m)
print('Get 2 first rows',m[:2])

2d array [[-1.73562356  2.51107654]
 [-1.25550422  3.15924845]
 [-0.2346154  -1.3344632 ]]
Get 2 first rows [[-1.73562356  2.51107654]
 [-1.25550422  3.15924845]]


In [34]:
n = np.random.randn(3,3)
print(n)
print()
print(n[1,:2],n[1,:2].size)
print()
print(n[1:2,:2],np.size(n[1:2,:2]))

[[-0.17841254  0.03423592 -1.78414018]
 [-0.49836781 -0.73080482 -0.36950105]
 [-0.74861938 -0.27210261 -1.78820784]]

[-0.49836781 -0.73080482] 2

[[-0.49836781 -0.73080482]] 2


In [39]:
data = np.random.randn(7,7)
print(data)
print()
names = np.array(('bob','tre','xyz','bob','tyr','buew','tyer'))
print(names)
print()
n = names == 'bob'
print(n)
print()
print(data[n])
print()
print(data[n,2:])

[[ 0.33077255 -0.65564308 -0.84459322  0.88225753 -0.55803419  1.28850924
   1.37593344]
 [-1.22238314 -0.28156909 -0.02213707  1.12641628 -0.04131128  0.59583817
   0.97048144]
 [-2.09156564 -1.24161625  0.90513956  0.14718696 -1.121061   -0.09283679
   1.78290084]
 [-0.64820456 -0.43559819  0.04955469  1.21635357 -0.21965375  0.18164246
   0.77521107]
 [ 1.5054135  -0.30575013 -0.3505635   0.42182446  0.57211235 -0.25777353
   0.09904505]
 [ 1.37755204 -0.17682649 -0.59023336  1.46016381 -1.4031355   0.67302429
  -1.3099569 ]
 [ 0.49379862  1.33640865 -0.18170617  0.62090681 -0.80233611  1.22739183
   0.44325001]]

['bob' 'tre' 'xyz' 'bob' 'tyr' 'buew' 'tyer']

[ True False False  True False False False]

[[ 0.33077255 -0.65564308 -0.84459322  0.88225753 -0.55803419  1.28850924
   1.37593344]
 [-0.64820456 -0.43559819  0.04955469  1.21635357 -0.21965375  0.18164246
   0.77521107]]

[[-0.84459322  0.88225753 -0.55803419  1.28850924  1.37593344]
 [ 0.04955469  1.21635357 -0.21965375  0

In [52]:
n = np.random.rand(8,4)
print(n)
print()
print(n[[1,2,4],[0,2,3]])

[[0.63030067 0.17016087 0.4634657  0.21671258]
 [0.48478838 0.15016927 0.24768958 0.97705894]
 [0.86467649 0.72043238 0.59826206 0.06008265]
 [0.03341353 0.95962901 0.96165004 0.02644337]
 [0.98190866 0.62346099 0.62121874 0.71953526]
 [0.69043386 0.69152698 0.88624195 0.46062424]
 [0.19571026 0.02208573 0.07771336 0.28250694]
 [0.56821587 0.97161712 0.34243974 0.82261957]]

[0.48478838 0.59826206 0.71953526]


In [53]:
n = np.random.randn(4,4)
print(n)
print()
np.where(n > 0, 2,3)

[[-0.37781038  1.13647574  1.13028939  0.57963841]
 [ 1.11989823 -0.25909163  0.04042024 -0.31767318]
 [-0.05481429 -0.24476088 -0.40489063  0.98409774]
 [ 1.33207451 -0.74655638 -1.77932104 -0.18675632]]



array([[3, 2, 2, 2],
       [2, 3, 2, 3],
       [3, 3, 3, 2],
       [2, 3, 3, 3]])

In [70]:
y = np.linalg.inv(n)
np.dot(y, n)

array([[ 1.00000000e+00,  1.66533454e-16,  2.77555756e-16,
         1.38777878e-17],
       [ 0.00000000e+00,  1.00000000e+00,  2.22044605e-16,
         1.94289029e-16],
       [ 0.00000000e+00,  1.11022302e-16,  1.00000000e+00,
        -8.32667268e-17],
       [ 1.38777878e-17,  1.38777878e-17,  2.77555756e-17,
         1.00000000e+00]])