In [19]:
import numpy as np
from keras.datasets import mnist

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
x = np.array(12)

In [3]:
x.ndim

0

In [4]:
x

array(12)

In [5]:
x = np.array([12, 3, 6, 14])

In [8]:
x.ndim
x.shape

(4,)

In [9]:
 x = np.array([[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]])
x.ndim

2

In [10]:
x.shape

(3, 5)

In [16]:
x = np.array([[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]]])
x.shape

(3, 3, 5)

In [12]:
x.ndim

3

In [17]:
x

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]])

In [20]:
x = np.array([[[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]]]])
x

array([[[[ 5, 78,  2, 34,  0],
         [ 6, 79,  3, 35,  1],
         [ 7, 80,  4, 36,  2]],

        [[ 5, 78,  2, 34,  0],
         [ 6, 79,  3, 35,  1],
         [ 7, 80,  4, 36,  2]],

        [[ 5, 78,  2, 34,  0],
         [ 6, 79,  3, 35,  1],
         [ 7, 80,  4, 36,  2]]]])

In [21]:
x.ndim

4

In [22]:
x.shape

(1, 3, 3, 5)

In [23]:
x.dtype

dtype('int32')

In [26]:
x.stype()

AttributeError: 'numpy.ndarray' object has no attribute 'stype'

In [29]:
u = np.ones(shape=(2,3)) 

In [30]:
z = u *3

In [31]:
print(u,z)

[[1. 1. 1.]
 [1. 1. 1.]] [[3. 3. 3.]
 [3. 3. 3.]]


In [32]:
u*z

array([[3., 3., 3.],
       [3., 3., 3.]])

In [34]:
np.dot(u,z.reshape(3,2))

array([[9., 9.],
       [9., 9.]])

In [36]:
u@z.reshape(3,2)

array([[9., 9.],
       [9., 9.]])

In [37]:
np.mul(u,z)

AttributeError: module 'numpy' has no attribute 'mul'