In [2]:
import pandas as pd

In [5]:
obj = pd.Series([4,5,6,7,8])
obj

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [6]:
obj.values

array([4, 5, 6, 7, 8], dtype=int64)

In [7]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
obj2 = pd.Series([5,3,-2,1], index = ['d','a','v','t'])
obj2

d    5
a    3
v   -2
t    1
dtype: int64

In [9]:
obj2.index

Index(['d', 'a', 'v', 't'], dtype='object')

In [22]:
obj3 = pd.Series([5,3,-2,1,5], index = pd.RangeIndex(4, 14, 2))
obj3

4     5
6     3
8    -2
10    1
12    5
dtype: int64

In [24]:
obj2['e'] = 6
obj2

d    5
a    3
v   -2
t    1
e    6
dtype: int64

In [26]:
obj2[['a','d','e']]

a    3
d    5
e    6
dtype: int64

In [27]:
obj3 = pd.Series(['a',1,'b', False])
obj3

0        a
1        1
2        b
3    False
dtype: object

In [31]:
obj4 = pd.Series([4,3,2,6], index = ['a', 'v','d','a'])
print(obj4['a'])
obj4

a    4
a    6
dtype: int64


a    4
v    3
d    2
a    6
dtype: int64

In [32]:
obj5 = pd.Series([4,5,6,3], index = [('a','b'),'c','d','e'])
obj5

(a, b)    4
c         5
d         6
e         3
dtype: int64

In [36]:
4 in obj5.values

True

In [37]:
'c' in obj5

True

In [38]:
dict1 = {'a':'City','b':'Address','c':'Postal code','d':'Country'}
obj6 = pd.Series(dict1)
obj6

a           City
b        Address
c    Postal code
d        Country
dtype: object

In [51]:
li = ['ci','ad','pc','c']
obj7 = pd.Series(list(dict1.values()),index = li)
obj7

ci           City
ad        Address
pc    Postal code
c         Country
dtype: object

In [46]:
print(obj7.notnull())
print()
print(obj7.isnull())

ci    False
ad    False
pc    False
c      True
dtype: bool

ci     True
ad     True
pc     True
c     False
dtype: bool


In [53]:
dt = pd.date_range('2017-04-01','2017-04-06')
dt

DatetimeIndex(['2017-04-01', '2017-04-02', '2017-04-03', '2017-04-04',
               '2017-04-05', '2017-04-06'],
              dtype='datetime64[ns]', freq='D')

In [55]:
b1 = pd.Series([20,30,40,50,60,70],index = dt)
b1

2017-04-01    20
2017-04-02    30
2017-04-03    40
2017-04-04    50
2017-04-05    60
2017-04-06    70
Freq: D, dtype: int64

In [56]:
b1.mean()

45.0

In [57]:
b1.sum()

270

In [58]:
b1.max()

70

In [59]:
b1.min()

20

# DataFrame

In [70]:
data = {
    'state': ['ohio','ohio','ohio','Nevada','Nevada','Nevada'],
    'year' : [2000,2001,2002,2003,2004,2005],
    'pop':[1.5,1.7,2.4,3.6,2.9,3.2]
}
df = pd.DataFrame(data)
df

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  2.4
3  Nevada  2003  3.6
4  Nevada  2004  2.9
5  Nevada  2005  3.2

In [72]:
df.head(2)

state  year  pop
0  ohio  2000  1.5
1  ohio  2001  1.7

In [73]:
df.describe()

year       pop
count     6.000000  6.000000
mean   2002.500000  2.550000
std       1.870829  0.836062
min    2000.000000  1.500000
25%    2001.250000  1.875000
50%    2002.500000  2.650000
75%    2003.750000  3.125000
max    2005.000000  3.600000

In [79]:
df.columns

Index(['state', 'year', 'pop'], dtype='object')

In [82]:
df.columns = ['new','year','pop']
df

new  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  2.4
3  Nevada  2003  3.6
4  Nevada  2004  2.9
5  Nevada  2005  3.2

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
new     6 non-null object
year    6 non-null int64
pop     6 non-null float64
dtypes: float64(1), int64(1), object(1)
memory usage: 224.0+ bytes


In [84]:
df.tail()

new  year  pop
1    ohio  2001  1.7
2    ohio  2002  2.4
3  Nevada  2003  3.6
4  Nevada  2004  2.9
5  Nevada  2005  3.2

In [87]:
df2 = pd.DataFrame(data,columns = ['year','state','pop'], index = ['one','two','three','four','fice','six'])
df2

year   state  pop
one    2000    ohio  1.5
two    2001    ohio  1.7
three  2002    ohio  2.4
four   2003  Nevada  3.6
fice   2004  Nevada  2.9
six    2005  Nevada  3.2

In [88]:
df2 = pd.DataFrame(data,columns = ['year','state','pop','dept'], index = ['one','two','three','four','fice','six'])
df2

year   state  pop dept
one    2000    ohio  1.5  NaN
two    2001    ohio  1.7  NaN
three  2002    ohio  2.4  NaN
four   2003  Nevada  3.6  NaN
fice   2004  Nevada  2.9  NaN
six    2005  Nevada  3.2  NaN

In [89]:
df2.index

Index(['one', 'two', 'three', 'four', 'fice', 'six'], dtype='object')

In [95]:
df2[['state','year']]

state  year
one      ohio  2000
two      ohio  2001
three    ohio  2002
four   Nevada  2003
fice   Nevada  2004
six    Nevada  2005

In [96]:
df2.loc['three']

year     2002
state    ohio
pop       2.4
dept      NaN
Name: three, dtype: object

In [99]:
df2.iloc[0]

year     2000
state    ohio
pop       1.5
dept      NaN
Name: one, dtype: object

In [100]:
b2 = pd.Series([10,20,30,40,50,60],index = dt)
b2

2017-04-01    10
2017-04-02    20
2017-04-03    30
2017-04-04    40
2017-04-05    50
2017-04-06    60
Freq: D, dtype: int64

In [101]:
frame = pd.DataFrame({'new':b1,'second': b2})
frame

new  second
2017-04-01   20      10
2017-04-02   30      20
2017-04-03   40      30
2017-04-04   50      40
2017-04-05   60      50
2017-04-06   70      60

In [103]:
frame['three'] = frame.new - frame.second
frame

new  second  three
2017-04-01   20      10     10
2017-04-02   30      20     10
2017-04-03   40      30     10
2017-04-04   50      40     10
2017-04-05   60      50     10
2017-04-06   70      60     10

In [112]:
frame.ix[1,'three']

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


10

In [113]:
frame.three[1:3]

2017-04-02    10
2017-04-03    10
Freq: D, Name: three, dtype: int64

In [116]:
frame.ix[:,('three')]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


2017-04-01    10
2017-04-02    10
2017-04-03    10
2017-04-04    10
2017-04-05    10
2017-04-06    10
Freq: D, Name: three, dtype: int64

In [117]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [119]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [120]:
Z = np.arange(11)
print(Z)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [121]:
np.array(12)

array(12)

In [123]:
np.arange(20).reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])