In [5]:
import numpy as np

In [7]:
a = np.arange(0,12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
b = np.arange(2,14).reshape(3,4)
b

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [10]:
a@b

array([[ 26,  29,  32,  35],
       [ 80,  92, 104, 116],
       [134, 155, 176, 197],
       [188, 218, 248, 278]])

In [14]:
c = np.arange(0,12).reshape(4,3)
d = np.arange(2,14).reshape(4,3)
c*d

array([[  0,   3,   8],
       [ 15,  24,  35],
       [ 48,  63,  80],
       [ 99, 120, 143]])

In [18]:
np.size(c,1)

3

In [16]:
c.shape

(4, 3)

In [19]:
a < 2

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [21]:
(a < 2) | (a > 3)

array([[ True,  True, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [33]:
i = 0
def exp(x):
    global i
    r = x < 2 or x > 3
    if r: 
        i +=1
    return r
print(i)
r = np.vectorize(exp)(a)

0


In [34]:
a[r]

array([ 0,  1,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
s = np.arange(25)
print(s)
print(np.sum(s<10))
print(np.sum(s[s<10]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
10
45


In [53]:
n = np.random.randint(12,24+1,12).reshape(3,4)
print(n)
print('Even vector:', n % 2)
print('Even Sum:', np.sum(n[n%2 == 0]))
print('Odd vector',n % 2 != 0)
print('Odd Sum',np.sum(n[n % 2 != 0]))

[[21 20 12 14]
 [15 21 15 24]
 [14 15 21 19]]
Even vector: [[1 0 0 0]
 [1 1 1 0]
 [0 1 1 1]]
Even Sum: 84
Odd vector [[ True False False False]
 [ True  True  True False]
 [False  True  True  True]]
Odd Sum 127


In [58]:
e = a.ravel()
print(e,a)
print(id(a),id(e))

[ 0  1  2  3  4  5  6  7  8  9 10 11] [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
1839498412480 1839473601392


In [57]:
f = b.flatten()
print(f,b)
print(id(b),id(f))

[ 2  3  4  5  6  7  8  9 10 11 12 13] [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
1839498414800 1839473601712


In [63]:
a.transpose()
np.transpose(a)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [67]:
v = np.arange(9).reshape(3,3)

np.linalg.inv(v)

LinAlgError: Singular matrix

In [68]:
np.linalg.inv(np.mat("0 1 2;1 0 3;4 -3 8"))

matrix([[-4.5,  7. , -1.5],
        [-2. ,  4. , -1. ],
        [ 1.5, -2. ,  0.5]])

In [72]:
np.hstack((c,d))

array([[ 0,  1,  2,  2,  3,  4],
       [ 3,  4,  5,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10],
       [ 9, 10, 11, 11, 12, 13]])

In [73]:
np.vstack((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [75]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [78]:
np.dstack((c,d))

array([[[ 0,  2],
        [ 1,  3],
        [ 2,  4]],

       [[ 3,  5],
        [ 4,  6],
        [ 5,  7]],

       [[ 6,  8],
        [ 7,  9],
        [ 8, 10]],

       [[ 9, 11],
        [10, 12],
        [11, 13]]])

In [86]:
np.split(b,2,axis=1)

[array([[ 2,  3],
        [ 6,  7],
        [10, 11]]), array([[ 4,  5],
        [ 8,  9],
        [12, 13]])]

In [88]:
np.column_stack((c,d))

array([[ 0,  1,  2,  2,  3,  4],
       [ 3,  4,  5,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10],
       [ 9, 10, 11, 11, 12, 13]])

In [90]:
np.row_stack((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [95]:
a.sum()

66

In [94]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [93]:
c.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [96]:
(a < 5).any()

True