In [11]:
import numpy as np
arr_3d = np.arange(24).reshape(6,4)
print(arr_3d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [24]:
arr = arr_3d[2:4,1:3]
arr

array([[ 9, 10],
       [13, 14]])

In [31]:
arr = arr_3d[4:5,2:3]
arr

array([[18]])

In [33]:
arr_3d = np.arange(27).reshape(3,3,3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [43]:
arr =arr_3d[1:2,1:3,1:2]
print(arr)
print(arr.shape,arr.ndim)

[[[13]
  [16]]]
(1, 2, 1) 3


In [54]:
arr_5d = np.arange(75).reshape(5,3,5)
arr_5d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]],

       [[45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]]])

In [55]:
arr_5d[2:3,0:,3:4]

array([[[33],
        [38],
        [43]]])

In [57]:
arr_5d[3,2,2] = 100
arr_5d

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14]],

       [[ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44]],

       [[ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56, 100,  58,  59]],

       [[ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]]])

1- create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions.

In [66]:
dim = -1.3-2.5
dim

-3.8

In [60]:
div = np.linspace(-1.3,2.5,64)
div

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

In [72]:
np.arange(-1.3,2.5,0.0603)

array([-1.3   , -1.2397, -1.1794, -1.1191, -1.0588, -0.9985, -0.9382,
       -0.8779, -0.8176, -0.7573, -0.697 , -0.6367, -0.5764, -0.5161,
       -0.4558, -0.3955, -0.3352, -0.2749, -0.2146, -0.1543, -0.094 ,
       -0.0337,  0.0266,  0.0869,  0.1472,  0.2075,  0.2678,  0.3281,
        0.3884,  0.4487,  0.509 ,  0.5693,  0.6296,  0.6899,  0.7502,
        0.8105,  0.8708,  0.9311,  0.9914,  1.0517,  1.112 ,  1.1723,
        1.2326,  1.2929,  1.3532,  1.4135,  1.4738,  1.5341,  1.5944,
        1.6547,  1.715 ,  1.7753,  1.8356,  1.8959,  1.9562,  2.0165,
        2.0768,  2.1371,  2.1974,  2.2577,  2.318 ,  2.3783,  2.4386,
        2.4989])

In [71]:
(2.5+1.3)/(64-1)

0.06031746031746031

2- Generate an array of lengeth 3n filled with the cyclic pattern 1,2,3

3- Create an array of first 10 odd integers

In [75]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [78]:
np.linspace(1,19,10)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

4- create a 10x10 arrays of zeros and then frame it with a border of ones

In [93]:
arr = np.ones(100).reshape(10,10)
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [96]:
arr[1:9,1:9] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])